name: BorderHoarder
version: '${project.version}'
main: com.simondmc.borderhoarder.BorderHoarder
api-version: 1.19
authors: [ SimonDMC ]
description: Collect unique items to expand the border
website: https://simondmc.com

commands:
  startbordergame:
  viewcollecteditems:
  viewmissingitems:
  joinbordergame:
  iscollected: